### ISSUE TITLE
How best to go about adding more time to a running countdown? (ie needs 5 minutes more before the countdown is complete)?

### ISSUE THREAD

**Issue by Glenncito** [zhigang1992/ZGCountDownTimer#10]

**Comment by Glenncito** [comment]
I edited the .m file to include this method:
- (void)addTime
  {
  self.totalCountDownTime = self.totalCountDownTime + 5.0;  
  }

But what happens when I call this is that the timePassed value also jumps by 5.0, and even if I subtract 5 from timePassed at the same time it jumps back to 5.0 a second later.

**Comment by zhigang1992** [comment]
quick hack, you can actually add 5 mins to _countDownCompleteDate_

**Comment by zhigang1992** [comment]
Also this field is not open as public field, but you can use _valueForKey_
and _setValueForKey_ for this.
Sry I don't have time right now to implement this properly...

**Comment by Glenncito** [comment]
Thank you for your response :) I will play around.

**Comment by zhigang1992** [comment]
If you're modifying the code itself, then you don't need the _valueForKey_
and all...
Good luck

:)

**Comment by Glenncito** [comment]
Yes I am modifying the code itself :)

**Comment by Glenncito** [comment]
And here is the hack that I added to ZGCountDownTimer.m:
- (void)addTime
  {
  int timeToAdd = 5;
  NSDate *newDate = [self.countDownCompleteDate dateByAddingTimeInterval:timeToAdd];
  self.countDownCompleteDate = newDate;
  
  NSTimeInterval interval = 5.0;
  self.totalCountDownTime = self.totalCountDownTime + interval;
  
  ## }

seems to be working fine now :) Do you forsee any issues with this code?

Thanks for your help!

**Comment by zhigang1992** [comment]
That's 5 secs not 5 mins, right? It looks fine :)

**Comment by Glenncito** [comment]
indeed - just for now though. 5 minutes is too much time to wait when testing.
